### ISSUE TITLE
how to delete the userid when he hit refresh

### ISSUE THREAD

**Issue by lmas3009** [CleverProgrammers/nodejs-zoom-clone#12]
Can any one tell this

**Comment by codergautam** [comment]
What do you  mean delete userid?

**Comment by lmas3009** [comment]
> What do you  mean delete userid?

When the person hit refresh need to remove/delete his previous id

**Comment by Starbors** [comment]
learn code.

**Comment by Boopalan-M** [comment]
> > What do you  mean delete userid?
> 
> When the person hit refresh need to remove/delete his previous id

how can i add the functionality of admin wants to allow or deny the participants
