### ISSUE TITLE
Peer js screenshare ?

### ISSUE THREAD

**Issue by ChandanRabha** [CleverProgrammers/nodejs-zoom-clone#15]
The project runs completely well. My only issue is trying to do screenshare using peer js . I tried changing the media stream of the webcam video stream to my screen share video stream. But then the video just freezes in the peer connected to my room. It would be of great help if someone could manage to do swap the video mediaStream while our video stream is being transmitted to all the peers connected to us. Thanks again.

**Comment by aristotle73** [comment]
I dont get what you are saying, could u explain.

**Comment by ChandanRabha** [comment]
Hey, thanks for the reply, i already got my fix, i just used the replaceTrack method to change the video stream.
